### ISSUE TITLE
NLP0001: Compile consolidated Tibetan word list (MM24)

### ISSUE THREAD

**Issue by kaldan007** [OpenPecha/tibetan_word_list#1]
**Description**:
We have lots of dictionary with Tibetan word list. We would like to have a unique word list from those dictionary.

**Dictionary Sources**

- [x] Leipzip
- [x] liguatools
- [x] Monlam

**Completion Criteria**:
We need a unique word list from all those dictionary data.

**Subtask**
- [x] Write a script for LiguaTools dictionaries to parse the JSON file and extract the list of words in JSON format.
- [x] Write a script for Leipzip dictionaries to parse the TSV file and extract the list of words in JSON format.
- [x] Write a script to combine all the word list JSON files and generate a unique, consolidated word list in JSON format.

**Comment by jim-gyas** [comment]
### Combine Unique Tibetan Word List 
```
[
    "ཚེ་དབང་བསྟན་འཛིན་",
    "ཀངྐ་ཊ་ཀཿ",
    "གཏོར་དབང་བསྐུར་ཚུལ་",
    "རཱཀྵཱ་",
    "རྩིད་",
    "རླུང་མཚམས་",
    "ཀུ་དམ་",
    "ཏུནྟི་བྷཿ་",
    "ཐོག་མ་མེད་པ་",
    "གཤིན་རྗེའི་སྐྱེས་བུ་",
    "གྲོགས་འདེད་",
    "དཀར་སྤྲང་",

```
